name: pixel-vernissage
services:
  service:
    image: ghcr.io/zalanddmi/pixelvernissage:latest
    environment:
      ASPNETCORE_URLS: "http://*:5207"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
    volumes:
      - ./secrets.json/:/App/secrets.json
    ports:
      - "5207:5207"
